name: Update Google APIs Commit Hash

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions: {}

jobs:
  update_protobuf_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Extract latest commit hash from googleapis/googleapis and create PR
        env:
          RUN_ID: ${{ github.run_id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          (cd /tmp && git clone --depth=1 https://github.com/googleapis/googleapis)
          # comment
          export LATEST_COMMIT_HASH=$(cd /tmp/googleapis && git log -n 1 --format=%H)
          sed -i "s/^\(DEFAULT_GOOGLEAPIS_COMMIT\s*=\s*\).*/\1${LATEST_COMMIT_HASH}/" protoc-builder/versions.mk

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --type bool push.autoSetupRemote true
          git add -A
          git checkout -b googleapis-${RUN_ID}
          git commit -sam "Update GOOGLEAPIS_COMMIT in versions.mk"
          git push
          gh pr create --title "build(deps): Bump github.com/googleapis/googleapis to latest commit" \
            --body "This pull request updates the GOOGLEAPIS_COMMIT variable in protoc-builder/versions.mk with the latest commit hash from the googleapis/googleapis repository." \
            --base main \
            --head googleapis-${RUN_ID}
